
version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP for Go/Python communication
      - "15672:15672"   # Web UI for management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: vhost
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq
    #   - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

# volumes:
#   rabbitmq_data:
#   rabbitmq_logs:
