[project]
name = "pythonai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "opencv-contrib-python>=4.12.0.88",
    "pika>=1.3.2",
    "pillow>=11.3.0",
    "srsly>=2.5.1",
]
