
version: "3.8"

services:
  goserver:
    image: goserver
    ports:
      - 8090:8090
    command: ./server
    volumes:
      - ./goserver/config.yaml:/app/config.yaml
  pythonai:
    image: pythonai
    command: uv run ./main.py
    volumes:
      - ./pythonai/yolo/:/app/yolo
      - ./goserver/config.yaml:/app/config.yaml
    depends_on:
      - goserver
