esp32cam:
  url: http://192.168.0.107
  captureEndpoint: capture
  streamEndpoint: stream
fileSystem:
  imagesDir: images
capture:
  interval: 10
rabbitmq:
  port: !env_var RPORT 5672
  user: !env_var RUSER user
  pass: !env_var RPASS pass
  host: !env_var RHOST localhost
  vhost: !env_var RVHOST vhost
  queue: !env_var RQUEUE images
