esp32cam:
  url: http://192.168.15.117
  captureEndpoint: capture
  streamEndpoint: stream
fileSystem:
  imagesDir: images
capture:
  interval: 10
  save: false
goserver:
  base_url: http://localhost:8090
  capture_endpoint: capture
  upload_endpoint: ai
ai:
  interval: 0.25
